/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watersanitationgame.Input_Sian;

/**
 *
 * @author Sian
 */
import watersanitationgame.Events_Nikolas.EventsGUI;
import watersanitationgame.Save;

public class ConfirmDetailsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmDetailsGUI.class.getName());

    /**
     * Creates new form ConfirmDetailsGUI
     */
    //I want my userDetails in here
    private UserDetails userDetails;
    
    public ConfirmDetailsGUI(UserDetails userDetails) { //the values i need it to take from my userDetails
        initComponents();
        this.userDetails = userDetails;
        //Setting the fields to the info previously entered
        confirmNameTF.setText(userDetails.getName().getName());
        confirmAgeTF.setText(String.valueOf(userDetails.getAge().getAge()));
        confirmGenderTF.setText(userDetails.getGender().getGender());
        confirmCountryTF.setText(userDetails.getCountry().getCountry());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPNL = new javax.swing.JPanel();
        exitBTN = new javax.swing.JButton();
        confirmBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        confirmCountryTF = new javax.swing.JTextField();
        confirmGenderTF = new javax.swing.JTextField();
        confirmAgeTF = new javax.swing.JTextField();
        confirmNameTF = new javax.swing.JTextField();
        detailsTF = new javax.swing.JTextField();
        confirmNameLBL = new javax.swing.JLabel();
        confirmAgeLBL = new javax.swing.JLabel();
        confirmGenderLBL = new javax.swing.JLabel();
        confirmCountyLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPNL.setBackground(new java.awt.Color(51, 204, 255));

        exitBTN.setBackground(new java.awt.Color(204, 204, 204));
        exitBTN.setText("Exit");
        exitBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        confirmBTN.setBackground(new java.awt.Color(204, 204, 204));
        confirmBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmBTN.setText("Confirm");
        confirmBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBTNActionPerformed(evt);
            }
        });

        backBTN.setBackground(new java.awt.Color(204, 204, 204));
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        detailsTF.setBackground(new java.awt.Color(51, 204, 255));
        detailsTF.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        detailsTF.setText("These are your details:");

        confirmNameLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        confirmNameLBL.setText("Name:");

        confirmAgeLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        confirmAgeLBL.setText("Age:");

        confirmGenderLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        confirmGenderLBL.setText("Gender:");

        confirmCountyLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        confirmCountyLBL.setText("Country:");

        javax.swing.GroupLayout backgroundPNLLayout = new javax.swing.GroupLayout(backgroundPNL);
        backgroundPNL.setLayout(backgroundPNLLayout);
        backgroundPNLLayout.setHorizontalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(detailsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmNameLBL)
                            .addComponent(confirmAgeLBL)
                            .addComponent(confirmGenderLBL)
                            .addComponent(confirmCountyLBL))
                        .addGap(39, 39, 39)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmGenderTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(confirmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        backgroundPNLLayout.setVerticalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmNameLBL))
                .addGap(25, 25, 25)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmAgeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmAgeLBL))
                .addGap(26, 26, 26)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmGenderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmGenderLBL))
                .addGap(34, 34, 34)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmCountyLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBTNActionPerformed
        // TODO add your handling code here:
        //When the confirm button is pressed, add the user details to the ArrayList
        //Proceed to the next JFrame
        //Get out information
        
        //Create a new Save
        Save s = new Save(
        userDetails.getName().getName(),
        userDetails.getGender().getGender(),
        userDetails.getCountry().getCountry(),
        userDetails.getAge().getAge()
        );
        
        //Check if the user exists
        
        //Now add it to the ArrayList
        userDetails.getSlist().add(s);
        
        //Save the file
        userDetails.saveToFile();
        
        //Go to the next JFrame
        EventsGUI e = new EventsGUI(0);  //EventsGUI recquires a parameter
        e.setVisible(true);
        this.dispose(); //close the window

    }//GEN-LAST:event_confirmBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        //When the back button is clicked, we go back to NewUserGUI
        NewUserGUI nu = new NewUserGUI(userDetails);
        nu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        //When the exit button is clicked, we close the JFrame form
        dispose();
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form*/
        //java.awt.EventQueue.invokeLater(() -> new ConfirmDetailsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JPanel backgroundPNL;
    private javax.swing.JLabel confirmAgeLBL;
    private javax.swing.JTextField confirmAgeTF;
    private javax.swing.JButton confirmBTN;
    private javax.swing.JTextField confirmCountryTF;
    private javax.swing.JLabel confirmCountyLBL;
    private javax.swing.JLabel confirmGenderLBL;
    private javax.swing.JTextField confirmGenderTF;
    private javax.swing.JLabel confirmNameLBL;
    private javax.swing.JTextField confirmNameTF;
    private javax.swing.JTextField detailsTF;
    private javax.swing.JButton exitBTN;
    // End of variables declaration//GEN-END:variables
}
