/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watersanitationgame.Input_Sian;

/**
 *
 * @author Sian
 */
import javax.swing.JOptionPane; 
import watersanitationgame.Events_Nikolas.EventsGUI;
import watersanitationgame.Save;
public class NewUserGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewUserGUI.class.getName());

    /**
     * Creates new form UserDetailsGUI
     */
    //Creating my userDetails object
    private UserDetails userDetails;
    
    public NewUserGUI(UserDetails ud) {
        initComponents();
        this.userDetails = ud; //Initialise in my constructor, need the info from here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPNL = new javax.swing.JPanel();
        exitBTN = new javax.swing.JButton();
        newUserLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        clearBTN = new javax.swing.JButton();
        SubmitBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        ageTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        countryTF = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        ageLBL = new javax.swing.JLabel();
        genderLBL = new javax.swing.JLabel();
        countryLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPNL.setBackground(new java.awt.Color(51, 204, 255));

        exitBTN.setBackground(new java.awt.Color(204, 204, 204));
        exitBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        newUserLBL.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        newUserLBL.setText("New User");

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        clearBTN.setBackground(new java.awt.Color(204, 204, 204));
        clearBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        SubmitBTN.setBackground(new java.awt.Color(204, 204, 204));
        SubmitBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitBTN.setText("Submit");
        SubmitBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTNActionPerformed(evt);
            }
        });

        backBTN.setBackground(new java.awt.Color(204, 204, 204));
        backBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        nameLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        nameLBL.setText("Name:");

        ageLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        ageLBL.setText("Age:");

        genderLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        genderLBL.setText("Gender:");

        countryLBL.setFont(new java.awt.Font("sansserif", 1, 17)); // NOI18N
        countryLBL.setText("Country:");

        javax.swing.GroupLayout backgroundPNLLayout = new javax.swing.GroupLayout(backgroundPNL);
        backgroundPNL.setLayout(backgroundPNLLayout);
        backgroundPNLLayout.setHorizontalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(newUserLBL))
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLBL)
                            .addComponent(ageLBL)
                            .addComponent(genderLBL)
                            .addComponent(countryLBL))
                        .addGap(59, 59, 59)
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPNLLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        backgroundPNLLayout.setVerticalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPNLLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(newUserLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLBL)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLBL)
                    .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLBL)
                    .addComponent(countryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBTN)
                    .addComponent(clearBTN)
                    .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
        // TODO add your handling code here:
        //When the submit button is clicked, the user details are added to the userDetails, this is then stored in an ArrayList to be read by the other sections
        //Also if any of the fields are empty, pop an alert
        //Do not proceed to the next JFrame if the details are empty
        if (nameTF.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "Please enter a name"); 
           return;
        } 
        
        if (ageTF.getText().isEmpty()) { 
           JOptionPane.showMessageDialog(null, "Please enter an age"); 
            return;
        } 
        
        if (genderTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a gender"); 
             return;
        } 
        
        if (countryTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a country"); 
             return;
        }
        
        //Get the information from the fields and assign them to objects
        Name nme = new Name(nameTF.getText());
        Age a = new Age(Integer.parseInt(ageTF.getText()));
        Gender g = new Gender(genderTF.getText());
        Country c = new Country(countryTF.getText());
        
        //Update my object (for the next section)
        userDetails.setName(nme);
        userDetails.setAge(a);
        userDetails.setGender(g);
        userDetails.setCountry(c);

        //When the submit button is clicked, we proceed onto the ConfirmDetailsGUI
        //New:
        ConfirmDetailsGUI cf = new ConfirmDetailsGUI(userDetails);
        cf.setVisible(true);
        dispose();
    }//GEN-LAST:event_SubmitBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        //When the back button is clicked, we go back to the UserSearchGUI
        UserSearchGUI ser = new UserSearchGUI();
        ser.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        //When we click the exit button, the JFrame form closes
        dispose();
    }//GEN-LAST:event_exitBTNActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        //When the clear button is clicked, the user details they have entered are cleared, empty String
        nameTF.setText("");
        ageTF.setText("");
        genderTF.setText("");
        countryTF.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new NewUserGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton backBTN;
    private javax.swing.JPanel backgroundPNL;
    private javax.swing.JButton clearBTN;
    private javax.swing.JLabel countryLBL;
    private javax.swing.JTextField countryTF;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel genderLBL;
    private javax.swing.JTextField genderTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel newUserLBL;
    // End of variables declaration//GEN-END:variables
}
