/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watersanitationgame.Input_Sian;

import javax.swing.JOptionPane;
import watersanitationgame.Events_Nikolas.EventsGUI;
import watersanitationgame.Save;

/**
 *
 * @author Sian
 */
public class ReturningUserGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturningUserGUI.class.getName());

    /**
     * Creates new form ReturningUser
     */
    private UserDetails userDetails; //need access to the user details to check for the search button
    
    public ReturningUserGUI(UserDetails ud) {
        initComponents();
        this.userDetails = ud;//get access to my saved users (user details)
        userDetails.loadFromFile(); //load the details from my file (Save)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPNL = new javax.swing.JPanel();
        exitBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        returningUserLBL = new javax.swing.JLabel();
        clearBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        genderTF = new javax.swing.JTextField();
        countryTF = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        countryLBL = new javax.swing.JLabel();
        genderLBL = new javax.swing.JLabel();
        ageLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPNL.setBackground(new java.awt.Color(51, 204, 255));

        exitBTN.setBackground(new java.awt.Color(204, 204, 204));
        exitBTN.setText("Exit");
        exitBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        deleteBTN.setBackground(new java.awt.Color(204, 204, 204));
        deleteBTN.setText("Delete User");
        deleteBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        returningUserLBL.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        returningUserLBL.setText("Returning User");

        clearBTN.setBackground(new java.awt.Color(204, 204, 204));
        clearBTN.setText("Clear");
        clearBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        okBTN.setBackground(new java.awt.Color(204, 204, 204));
        okBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        okBTN.setText("OK");
        okBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        searchBTN.setBackground(new java.awt.Color(204, 204, 204));
        searchBTN.setText("Search");
        searchBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        countryLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        countryLBL.setText("Country:");

        genderLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderLBL.setText("Gender:");

        ageLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageLBL.setText("Age:");

        nameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLBL.setText("Name:");

        backBTN.setBackground(new java.awt.Color(204, 204, 204));
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPNLLayout = new javax.swing.GroupLayout(backgroundPNL);
        backgroundPNL.setLayout(backgroundPNLLayout);
        backgroundPNLLayout.setHorizontalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(returningUserLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundPNLLayout.createSequentialGroup()
                                .addComponent(countryLBL)
                                .addGap(18, 18, 18)
                                .addComponent(countryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundPNLLayout.createSequentialGroup()
                                    .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameLBL)
                                        .addComponent(ageLBL))
                                    .addGap(26, 26, 26)
                                    .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(backgroundPNLLayout.createSequentialGroup()
                                    .addComponent(genderLBL)
                                    .addGap(18, 18, 18)
                                    .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(okBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        backgroundPNLLayout.setVerticalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(returningUserLBL)
                    .addGroup(backgroundPNLLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(exitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLBL))
                .addGap(28, 28, 28)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLBL))
                .addGap(18, 18, 18)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLBL)
                    .addComponent(genderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLBL)
                    .addComponent(countryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBTN)
                    .addComponent(clearBTN)
                    .addComponent(okBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        //When the back button ic clicked, we go back to the UserSearchGUI
        UserSearchGUI ser = new UserSearchGUI();
        ser.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        //When the exit button is clicked, we exit the JFrame form
        dispose();
    }//GEN-LAST:event_exitBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        // TODO add your handling code here:
        //Check to make sure the user entered details
        //Do not proceed to the next JFrame if the details are empty
         if (nameTF.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "Please enter a name"); 
            return;
        } 
        
        if (ageTF.getText().isEmpty()) { 
           JOptionPane.showMessageDialog(null, "Please enter an age"); 
            return;
        } 
        
        if (genderTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a gender");
             return;
        } 
        
        if (countryTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a country");
             return;
        }
        //When this button is clicked, proceed onto the events section 
        EventsGUI n = new EventsGUI(0); //events parameter
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_okBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        //When the search button is clicked, the user details pop up in the text boxes?
        //Make sure the fields are not null
         if (nameTF.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "Please enter a name"); 
            return;
        } 
        
        if (ageTF.getText().isEmpty()) { 
           JOptionPane.showMessageDialog(null, "Please enter an age"); 
            return;
        } 
        
        if (genderTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a gender");
             return;
        } 
        
        if (countryTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a country");
             return;
        }
        
        boolean found = false;

        //get the info from here
        String searchForName = nameTF.getText();
        String searchForAge  = ageTF.getText();
        String searchForGender = genderTF.getText();
        String searchForCountry = countryTF.getText();

        //for loop for my ArrayList/Save file
        for (Save s : userDetails.getSlist()) {

            //Make sure all details match so the wrong user doesn't get deleted
            if (s.getName().equalsIgnoreCase(searchForName) &&
                String.valueOf(s.getAge()).equals(searchForAge) &&
                s.getGender().equalsIgnoreCase(searchForGender) &&
                s.getCountry().equalsIgnoreCase(searchForCountry)) {

                //Populate the text fields
                nameTF.setText(s.getName());
                ageTF.setText(String.valueOf(s.getAge()));
                genderTF.setText(s.getGender());
                countryTF.setText(s.getCountry());

                found = true;
                JOptionPane.showMessageDialog(null, "User found!");
                break; //come out of the loop
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(null, "User not found!");
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        //When the clear button is clicked the user details are cleared, empty Strings
        nameTF.setText("");
        ageTF.setText("");
        genderTF.setText("");
        countryTF.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        //When the delete button is clicked the user details are deleted    
        //check if it's empty
        if (nameTF.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Enter a name");
        return;
    }
        if (ageTF.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Enter your age");
        return;
    }
        if (genderTF.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Enter your gender");
        return;
    }
        if (ageTF.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Enter where you're from");
        return;
    }
        
        //get the details from the fields
        String searchName = nameTF.getText();
        String searchAge = ageTF.getText();
        String searchGender = genderTF.getText();
        String searchCountry = countryTF.getText();
        
        boolean found = false;
        
        //for loop
        for (int i = 0; i < userDetails.getSlist().size(); i++) {
            Save s = userDetails.getSlist().get(i);
            if (s.getName().equalsIgnoreCase(searchName) &&
            String.valueOf(s.getAge()).equals(searchAge) &&
            s.getGender().equalsIgnoreCase(searchGender) &&
            s.getCountry().equalsIgnoreCase(searchCountry)) {
                
            userDetails.getSlist().remove(i); //remove what's at the index
            userDetails.saveToFile(); //save the file
            JOptionPane.showMessageDialog(null, "User details have been deleted!");
            
            //set the text fields to empty fields
            nameTF.setText("");
            ageTF.setText("");
            genderTF.setText("");
            countryTF.setText("");

            found = true; //change the boolean value
            break; //come out of the loop
    }
}
        //If no user was found
        if (!found) {
            JOptionPane.showMessageDialog(null, "User not found!");
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UserDetails ud = new UserDetails(); //accessing my userDetails
        ud.loadFromFile(); //load my file
        java.awt.EventQueue.invokeLater(() -> new ReturningUserGUI(ud).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton backBTN;
    private javax.swing.JPanel backgroundPNL;
    private javax.swing.JButton clearBTN;
    private javax.swing.JLabel countryLBL;
    private javax.swing.JTextField countryTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel genderLBL;
    private javax.swing.JTextField genderTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel returningUserLBL;
    private javax.swing.JButton searchBTN;
    // End of variables declaration//GEN-END:variables
}
