/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watersanitationgame.Ending_Jesse;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import watersanitationgame.Save;

/**
 *
 * @author jesse
 */
public class PastResultsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PastResultsGUI.class.getName());
    ArrayList<Save> sList = new ArrayList<>();
    Save selectedSave;
    EndingCalculation endingCalculation;
    int saveIndex;
    
    /**
     * Creates new form PastResultsGUI
     */
    public PastResultsGUI() {
        initComponents();
        endingCalculation = EndingCalculation.getInstance();
        sList = endingCalculation.getsList();
        selectedSave = null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        searchbyLBL = new javax.swing.JLabel();
        playernameRB = new javax.swing.JRadioButton();
        countryRB = new javax.swing.JRadioButton();
        searchBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        displayBTN = new javax.swing.JButton();
        viewBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        tutorialBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        savenameRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchbyLBL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchbyLBL.setText("Search By: ");

        buttonGroup1.add(playernameRB);
        playernameRB.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        playernameRB.setText("Player Name");

        buttonGroup1.add(countryRB);
        countryRB.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        countryRB.setText("Country");

        searchBTN.setText("SEARCH");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        displayTA.setColumns(20);
        displayTA.setRows(5);
        displayTA.setText("Select option below to choose search\nmethod.\n\nOnce a save has been selected it will\napear in this text area. Click DELETE to \ndelete the selected save or VIEW to \nview the results of the save.\n");
        jScrollPane1.setViewportView(displayTA);

        displayBTN.setText("DISPLAY ALL");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        viewBTN.setText("VIEW");
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });

        deleteBTN.setText("DELETE");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        tutorialBTN.setText("SHOW TUTORIAL");
        tutorialBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialBTNActionPerformed(evt);
            }
        });

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        buttonGroup1.add(savenameRB);
        savenameRB.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        savenameRB.setText("Save Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchbyLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(searchBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tutorialBTN, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(savenameRB)
                            .addComponent(displayBTN))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(deleteBTN)
                                .addGap(18, 18, 18)
                                .addComponent(viewBTN))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(playernameRB, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(countryRB)
                                .addGap(135, 135, 135)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(exitBTN)
                        .addGap(36, 36, 36)
                        .addComponent(tutorialBTN)))
                .addGap(24, 24, 24)
                .addComponent(searchbyLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryRB)
                    .addComponent(playernameRB, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savenameRB))
                .addGap(18, 18, 18)
                .addComponent(searchBTN)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBTN)
                    .addComponent(deleteBTN)
                    .addComponent(viewBTN))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed

        
        if (sList.size() < 1){
            displayTA.setText("There are no saves");
            
        }else{
            for (Save tempS: sList){
                
                if (displaySaveJOption(tempS)){
                    break;
                }

            }
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed
        ResultsGUI resultsGUI = new ResultsGUI(selectedSave, true);
        resultsGUI.setVisible(true);
    }//GEN-LAST:event_viewBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBTNActionPerformed

    private void tutorialBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialBTNActionPerformed
        displayTA.setText("Select option below to choose search\n" +
        "method.\n" +
        "\n" +
        "Once a save has been selected it will\n" +
        "apear in this text area. Click DELETE to \n" +
        "delete the selected save or VIEW to \n" +
        "view the results of the save.\n");
    }//GEN-LAST:event_tutorialBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed

        StringBuffer sBuff = new StringBuffer();
        
        if (playernameRB.isSelected()){
            
            String searchTerm = JOptionPane.showInputDialog("Enter in name to search");
            
            for (Save tempS: sList){
                if (tempS.getName().equalsIgnoreCase(searchTerm)){
                    if (displaySaveJOption(tempS)){
                        break;
                    }
                }
            }
            
        }else if (savenameRB.isSelected()){
            String searchTerm = JOptionPane.showInputDialog("Enter in country to search");
            
            for (Save tempS: sList){
                if (tempS.getSaveName().equalsIgnoreCase(searchTerm)){
                    if (displaySaveJOption(tempS)){
                        break;
                    }
                }
            }
        } else if (countryRB.isSelected()){
            String searchTerm = JOptionPane.showInputDialog("Enter in country to search");
            
            for (Save tempS: sList){
                if (tempS.getCountry().equalsIgnoreCase(searchTerm)){
                    if (displaySaveJOption(tempS)){
                        break;
                    }
                }
            }
        }
  
    }//GEN-LAST:event_searchBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        sList.remove(selectedSave);
        save();
        displayTA.setText("Save was deleted");
    }//GEN-LAST:event_deleteBTNActionPerformed

    private boolean displaySaveJOption(Save save){
        
            StringBuffer sBuff = new StringBuffer();
        
            Object[] options1 = { "Select", "Next"};
            sBuff.append("Save Name: ");
            sBuff.append(save.getSaveName());
            sBuff.append("\n");
            sBuff.append("Name: ");
            sBuff.append(save.getName());
            sBuff.append("\n");
            sBuff.append("Gender: ");
            sBuff.append(save.getGender());
            sBuff.append("\n");
            sBuff.append("Country: ");
            sBuff.append(save.getCountry());
            sBuff.append("\n");
            sBuff.append("Age: ");
            sBuff.append(save.getAge());
            
            
            int result = JOptionPane.showOptionDialog(null,  sBuff.toString(), save.getSaveName(), JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null, options1, null);
            sBuff.setLength(0);
            
            if (result == 0){
                selectedSave = save;
                displaySave(selectedSave);
                return true;
            }
            
            return false;
    
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PastResultsGUI().setVisible(true));
    }
    
    
    
    public void save(){
        
        endingCalculation.save();
    }
    
    public void displaySave(Save save){
        
        StringBuffer sBuff = new StringBuffer();
        
        sBuff.append("Save Name: ");
        sBuff.append(save.getSaveName());
        sBuff.append("\n");
        sBuff.append("Name: ");
        sBuff.append(save.getName());
        sBuff.append("\n");
        sBuff.append("Gender: ");
        sBuff.append(save.getGender());
        sBuff.append("\n");
        sBuff.append("Country: ");
        sBuff.append(save.getCountry());
        sBuff.append("\n");
        sBuff.append("Age: ");
        sBuff.append(save.getAge());
        
        displayTA.setText(sBuff.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton countryRB;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton playernameRB;
    private javax.swing.JRadioButton savenameRB;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel searchbyLBL;
    private javax.swing.JButton tutorialBTN;
    private javax.swing.JButton viewBTN;
    // End of variables declaration//GEN-END:variables
}

