/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package watersanitationgame.Ending_Jesse;

import javax.swing.JOptionPane;
import watersanitationgame.Save;

/**
 *
 * @author jesse
 */
public class ResultsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResultsGUI.class.getName());
    private int counter;
    private Save currentSave;
    private Boolean pastSave;
    EndingCalculation endingCalculation;
    /**
     * Creates new form resultsGUI
     * @param save
     */
    public ResultsGUI(Save save, Boolean past) {
        initComponents();
        currentSave = save;
        counter = 1;
        endingCalculation = EndingCalculation.getINSTANCE();
        pastSave = past;
        displayText();
        
    }

    private ResultsGUI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        nextBTN = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(225, 224, 224));

        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        nextBTN.setText("NEXT");
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });

        closeBTN.setText("CLOSE");
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });

        eventTA.setColumns(20);
        eventTA.setRows(5);
        jScrollPane1.setViewportView(eventTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextBTN)
                        .addGap(263, 263, 263))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(closeBTN)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBTN)
                    .addComponent(nextBTN))
                .addGap(18, 18, 18)
                .addComponent(closeBTN)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        
        if (counter != 1){
            counter--;
            displayText();
        }
    }//GEN-LAST:event_backBTNActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBTNActionPerformed

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        int choice1;
        int choice2;
        String saveName;
        
        
        if (counter != 5){
            counter++;
            displayText();
        }else{
            if (!pastSave){
                choice1 = JOptionPane.showConfirmDialog(null, "Do you want to save your results?");
                if (choice1 == 0){
                    saveName = JOptionPane.showInputDialog("What do you want to name your save?");
                    currentSave.setSaveName(saveName);
                    endingCalculation.getsList().add(currentSave);
                    
                    endingCalculation.save();
                }

                choice2 = JOptionPane.showConfirmDialog(null, "Do you want to quit?", null , 1);

                if (choice2 == 0){
                    System.exit(0);
                }
            }else{
                dispose();
            }

        }
         
    }//GEN-LAST:event_nextBTNActionPerformed

    
    private void displayText(){
        String text = "";
        
        text += "EVENT: ";
        
        switch (counter) {
            case 1 -> {
                text += "Firstly, you receive a report stating that safety standards in water treatment plants around the country are below standard.";
                text += "\n\n\n";
                text += "CHOICE: ";
                if (currentSave.isBeganSafetyInspections()){
                    text += "You chose to conduct safty inspections";
                }else{
                    text += "You chose to not conduct safty inspections";
                }       text += "\n\n\n";
                text += "EXPLANATION: ";
                text += "It is important that saftey inspections are made regularly to ensure our water quality is up to standard";
            }
            case 2 -> {
                text += "Some time later, you are invited to give a couple words to the press about your new position, \nthey ask for a quote about what kind of policy you might enact";
                text += "\n\n\n";
                text += "CHOICE: ";
                if (currentSave.isInterviewAnswer()){
                    text += "You chose to be honest with the media";
                }else{
                    text += "You chose to lie to the media";
                }       text += "\n\n\n";
                text += "EXPLANATION: ";
                text += "Transparency with the public is an important principle all public officals should hold to.";
            }
            case 3 -> {
                text += "A couple months later, you receive an alarming report. The water flowing to a specific town has been contaminated,\n due to a sewage network overflowing nearby a water distribution channel. What shall be done about this?";
                text += "\n\n\n";
                text += "CHOICE: ";
                if (currentSave.isRedirectedWater()){
                    text += "You chose to redirect the water flow ensuring clean water";
                }else{
                    text += "You chose to fix the sewage pipes";
                }       text += "\n\n\n";
                text += "EXPLANATION: ";
                text += "Although the sweage pipes needed to be repaired, it was more important to ensure that the town had clean water";
            }
            case 4 -> {
                text += "As you prepare to leave the facility, the manager of it shakes your hand and slips a thick envelope into it with a smile. \nOnce outside you manage to check the contents and find a large amount of money, \nenough to keep your personal bills and responsibilities  in check for a season...";
                text += "\n\n\n";
                text += "CHOICE: ";
                if (currentSave.isTookBribe()){
                    text += "You chose to take a bribe";
                }else{
                    text += "You rejected the bribe";
                }       text += "\n\n\n";
                text += "EXPLANATION: ";
                text += "Bribery is a very large concern when it comes to governing bodies. Bribes can cause extreme damage to \ninstituations that cause ordinary people to suffer.";
            }
            case 5 -> {
                text += "for the next few months, you find yourself dealing with a massive amount of paperwork, so much so that you realise \nyou are spending almost no time at home or with family, rarely relaxing. You think about what you might do about it all?";
                text += "\n\n\n";
                text += "CHOICE: ";
                if (currentSave.isStayedInOffice()){
                    text += "You chose grind out the paper work";
                }else{
                    text += "You chose to go on vacation with your family";
                }       text += "\n\n\n";
                text += "EXPLANATION: ";
                text += "Although it is important to relax now and again, public officals have the resonsability of many people \non their shoulders and should therefore ensure their work is finished before taking personal time.";
            }
            default -> {
            }
        }
       
       eventTA.setText(text);
   }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ResultsGUI().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton closeBTN;
    private javax.swing.JTextArea eventTA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBTN;
    // End of variables declaration//GEN-END:variables
}
